### ISSUE TITLE
Not full height

### ISSUE THREAD

**Issue by EmilMoe** [victorcwai/Android-App-Webview-AdBanner-Template#2]
I tried this, but when I open it on my phone, it will not stretch for a full height. Should I do something on the website to achieve this?

**Comment by vcwai** [comment]
Hmm I think you can try setting the height of your pages

**Comment by EmilMoe** [comment]
It works if I use pixel height, but I can't know the height of all screens of course. It seems `vh` and `%` doesn't work, but I will try again an extra time.

**Comment by EmilMoe** [comment]
I found the error and created a pull request: https://github.com/victorcwai/Android-App-Webview-AdBanner-Template/pull/3
